apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  labels: 
    app.kubernetes.io/instance: rag-oct24-2
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name:  rag-oct24-2
    app.kubernetes.io/part-of: rag-oct24-2  
  name: rag-oct24-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance:  rag-oct24-2 
  template:
    metadata: 
      labels:
        app.kubernetes.io/instance:  rag-oct24-2
    spec:
      containers:
      - image:  quay.io/redhat-ai-dev/ai-template-bootstrap-app:latest
        name: app-inference
        envFrom:
        - configMapRef:
            name: rag-oct24-2-model-config
        - configMapRef:
            name: rag-oct24-2-database-config
        env:
        - name: MODEL_ENDPOINT_BEARER
          valueFrom:
            secretKeyRef:
              name: modelserver-secret
              key: api_key
        ports:
        - containerPort: 8501
        securityContext:
          runAsNonRoot: true
